oh btw the game crashes when you reach level 35

** current list of minor bugs:

- players don't take damage unless player is on enemy tile during enemy activation tick
- knockback can knock enemies into the void
- players collide with corners between 2+ rooms, probably wontfix
- if pushing up against a wall and moving in the x axis, it is possible to get stuck in the edge between rooms
- old non-format trophy tiles are called "silver/gold/bronze 0"

** really have to be done by sunday 8pm todos

- [X] progress bar not actually showing progress to next level
- [X] make the dumb progression less dumb
- [X] background music and sfx
- [X] enemy spawning per map
- [X] being able to progress to another map
- [X] ending?
- [ ] saving player in browser
- [X] what do when player is ded??
- [X] disable weapon for n00b class, give each class some unique weapon

** botb description

you have been banished by the omnipotent baron to the dungeons of botb, filled with bugs, zombis, mummis and other hostile creatures, you may not leave the endless dungeon unless you become the grand wizard (i.e. get to level 33)

use the WASD layout (or equivalent for your keyboard layout) to move your character, and use the mouse to move your weapon, click to fire. take note that you can hold down the left mouse key to auto-fire your weapon. this game is best played using a mouse and keyboard. feel free to resize your screen (with ctrl+scrollwheel or ctrl+plus and ctrl+minus) if it's a bit too small.

every level in the dungeon is procedurally generated. you can progress to the next level once you have defeated all enemies on your current level, at this point a button will appear at the bottom of the screen allowing you to go down to the next level of the dungeon.

more enemies spawn as you continue down into each proceeding level, including a greater variety of enemies:

level 0: bugs and rats
level 1: pumpkings and bats
level 2: zombis
level 3: mummis and ghosts

(this includes 3 "unique" enemy AI)

currently there are 3 different classes you can choose from: hostist, grafxicist and chipist though in the current version of this game these classes are purely cosmetic and don't offer unique abilities/weapons. however, make sure to choose one at the beginning of the game, as the initial n00b class doesn't have any weapon!

the game actually uses a xp and level system which is similar to the botb level system, however I added an extra bonus per level so that you can progress through the game pretty quickly (it only takes about 3-4 levels in my testing). if you try and get to level 35 somehow the game will crash (I left that in because I thought it was funny)

read the bugs.txt file for minor game bugs to look out for while playing
